adminUser: admin
adminPassword: admin
service:
  type: NodePort
  nodePort: 30009
persistence:
  enabled: false
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.sentiment-app.svc.cluster.local:80
        access: proxy
        isDefault: true
        editable: true
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    spring-boot:
      gnetId: 12900
      revision: 1
      datasource: Prometheus
    jvm-micrometer:
      gnetId: 4701
      revision: 7
      datasource: Prometheus
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
securityContext:
  runAsNonRoot: true
  runAsUser: 472
  fsGroup: 472
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  analytics:
    check_for_updates: false
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
